### ISSUE TITLE
UNC messes up file paths

### ISSUE THREAD

**Issue by ghost** [oberien/rebo#2]
In `test.re`, line `278:8`, UNC makes the path return `\\?\C:\Users\sawar\rebo`. In the rust standard library, the UNC path
`\\?\C:\Users\sawar\rebo` does not start with `C:\Users`. Therefore, when oberien checks in Rebo that the file to be included is in the include directory, that check fails.

tl;dr Windows is dogshit and annoying af.

**Comment by oberien** [comment]
Fixed in 4f8074a76e40c8d7e34dab774cdd296e147dce35.
